### ISSUE TITLE
avconv problem

### ISSUE THREAD

**Issue by photoJames** [skiwithpete/timelapsepi#1]
I've followed the directions at the beginning and created the directories however I get the following error and no file is created.

converting to film now
sh: 1: avconv: not found
moving completed mp4 file
mv: cannot stat ‘*.mp4’: No such file or directory

I saw that someone else posted a similar issue on the youtube comments.

**Comment by skiwithpete** [comment]
if avconv not found then you have not correctly installed 

look at the instructions again and make sure that apt-get install libav-tools (or something similar) has been installed.

**Comment by photoJames** [comment]
Thanks, I'll try again. I believe that I did the apt-get install.

Cheers!
James

On Jul 20, 2017 6:03 AM, "skiwithpete" <notifications@github.com> wrote:

if avconv not found then you have not correctly installed

look at the instructions again and make sure that apt-get install
libav-tools (or something similar) has been installed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/skiwithpete/timelapsepi/issues/1#issuecomment-316696115>,
or mute the thread
